version: '3.8'

services:
  thesis-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/MY-Thesis
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HOST_IP=host.docker.internal
    command: /bin/bash -c "while true; do echo 'Container is running'; sleep 3600; done"
