version: '3.8'

services:
  thesis-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST_IP=host.docker.internal
    volumes:
      - .:/usr/src/MY-Thesis
    ports:
      - "80:80"    # Map TCP port 80 in the container to port 80 on the Docker host
      - "443:443"  # Map TCP port 443 in the container to port 443 on the Docker host
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
